name: Upload to Pypi

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      overrideVersion:
        description: Manually force a version

env:
  SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.inputs.overrideVersion }}

jobs:
  build:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install deps
      run: python -m pip install build twine
    - name: Build wheel and source tarball
      run: python -m build --sdist --wheel
    - uses: actions/upload-artifact@v2
      with:
        path: dist/
    - name: Check metadata
      run: twine check dist/*

  upload_all:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
